### PR TITLE
Fix path resolution of the directory whose name included glob special chars

### LINKED ISSUE #227: Server Mode will not start if absolute path to presentation contains opening parentheses `(`
trying to run marp-cli in server mode fails if the directory ( or any directory in the absolut path to the directory ) contains an opening parenthesis `(`. for example:

`marp -s -I hello\(world`

will bring up the *Usage Page* instead of starting *Server Mode*. this behavior occurs on MacOS 10.15 in bash shell.

### PR DESCRIPTION
**Pull request by yhatt**
Similar to #117 but it's for the directory path. Fix #227.

### CODE REVIEW

File: src/file.ts [hunk 1]
```diff
@@ -184,13 +188,12 @@ export class File {
...
-        absolute: true,
-        ignore: ['**/node_modules'],
-        ...opts,
-      })
-    ).forEach((p) => filepaths.add(p))
+    const gOpts = { absolute: true, ignore: ['**/node_modules'], ...opts }
+    ;(await globby(globs, gOpts)).forEach((p) => filepaths.add(p))
+
+    for (const cwd of dirs) {
+      ;(await globby('.', { cwd, ...gOpts })).forEach((p) => filepaths.add(p))
```
Comment (yhatt) [inline src/file.ts:195]: Expanding file patterns won't work in escaped glob path so we are using `cwd` option to specify the base directory.
